name: 'Configure AWS Credentials'
description: 'Configure AWS credentials using OIDC authentication'

inputs:
  role-arn:
    description: 'AWS IAM Role ARN to assume'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
  session-name:
    description: 'Role session name'
    required: false
    default: 'GitHubActionsSession'

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-arn }}
        aws-region: ${{ inputs.aws-region }}
        role-session-name: ${{ inputs.session-name }}
