name: 'Docker Build and Push to Docker Hub'
description: 'Build Docker image and push to Docker Hub with multiple tags'

inputs:
  dockerhub-username:
    description: 'Docker Hub username'
    required: true
  dockerhub-token:
    description: 'Docker Hub access token'
    required: true
  repository:
    description: 'Docker Hub repository name (e.g., username/repo-name)'
    required: true
  working-directory:
    description: 'Working directory containing Dockerfile'
    required: true
  image-tag:
    description: 'Primary image tag (e.g., git SHA)'
    required: true
  dockerfile:
    description: 'Path to Dockerfile relative to working-directory'
    required: false
    default: 'Dockerfile'
  extra-args:
    description: 'Additional Docker build arguments'
    required: false
    default: ''
  enable-cache:
    description: 'Enable Docker layer caching from latest tag'
    required: false
    default: 'true'
  push-latest:
    description: 'Also tag and push as latest (usually for main branch)'
    required: false
    default: 'false'
  additional-tags:
    description: 'Comma-separated additional tags (e.g., v1.0.0,stable)'
    required: false
    default: ''

outputs:
  image-tag:
    description: 'Primary image tag used'
    value: ${{ steps.set-outputs.outputs.image-tag }}
  image-uri:
    description: 'Full image URI with primary tag'
    value: ${{ steps.set-outputs.outputs.image-uri }}
  all-tags:
    description: 'All tags applied to the image'
    value: ${{ steps.set-outputs.outputs.all-tags }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Pull latest image for cache (if enabled)
      if: inputs.enable-cache == 'true'
      shell: bash
      env:
        REPOSITORY: ${{ inputs.repository }}
      run: |
        echo "Pulling latest image for layer caching..."
        docker pull $REPOSITORY:latest || echo "No cached image found, building from scratch"

    - name: Build and push Docker image to Docker Hub
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        REPOSITORY: ${{ inputs.repository }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        PUSH_LATEST: ${{ inputs.push-latest }}
        ADDITIONAL_TAGS: ${{ inputs.additional-tags }}
        ENABLE_CACHE: ${{ inputs.enable-cache }}
      run: |
        echo "Building Docker image for Docker Hub..."
        echo "Repository: $REPOSITORY"
        echo "Primary Tag: $IMAGE_TAG"

        # Build primary tag
        TAGS="-t $REPOSITORY:$IMAGE_TAG"
        ALL_TAGS="$IMAGE_TAG"

        # Add latest tag if enabled
        if [ "$PUSH_LATEST" == "true" ]; then
          TAGS="$TAGS -t $REPOSITORY:latest"
          ALL_TAGS="$ALL_TAGS,latest"
          echo "Adding tag: latest"
        fi

        # Add additional custom tags
        if [ -n "$ADDITIONAL_TAGS" ]; then
          IFS=',' read -ra EXTRA_TAGS <<< "$ADDITIONAL_TAGS"
          for tag in "${EXTRA_TAGS[@]}"; do
            tag=$(echo "$tag" | xargs)  # Trim whitespace
            if [ -n "$tag" ]; then
              TAGS="$TAGS -t $REPOSITORY:$tag"
              ALL_TAGS="$ALL_TAGS,$tag"
              echo "Adding tag: $tag"
            fi
          done
        fi

        # Prepare cache-from argument
        CACHE_ARG=""
        if [ "$ENABLE_CACHE" == "true" ]; then
          CACHE_ARG="--cache-from $REPOSITORY:latest"
        fi

        # Build the image with all tags
        echo "Building with tags: $ALL_TAGS"
        docker build \
          ${{ inputs.extra-args }} \
          $CACHE_ARG \
          $TAGS \
          -f ${{ inputs.dockerfile }} .

        # Push all tags at once
        echo "Pushing all tags to Docker Hub..."
        docker push $REPOSITORY --all-tags

        echo "✅ Image pushed: $REPOSITORY:$IMAGE_TAG"
        echo "all-tags=$ALL_TAGS" >> $GITHUB_ENV

    - name: Set outputs
      id: set-outputs
      shell: bash
      env:
        REPOSITORY: ${{ inputs.repository }}
        IMAGE_TAG: ${{ inputs.image-tag }}
      run: |
        echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
        echo "image-uri=$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
        echo "all-tags=${{ env.all-tags }}" >> $GITHUB_OUTPUT

    - name: Image summary
      shell: bash
      env:
        REPOSITORY: ${{ inputs.repository }}
        IMAGE_TAG: ${{ inputs.image-tag }}
      run: |
        echo "### Docker Hub Push Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Repository:** \`$REPOSITORY\`" >> $GITHUB_STEP_SUMMARY
        echo "**Primary Tag:** \`$IMAGE_TAG\`" >> $GITHUB_STEP_SUMMARY
        echo "**All Tags:** \`${{ env.all-tags }}\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Image URI:** \`$REPOSITORY:$IMAGE_TAG\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ Successfully pushed to Docker Hub" >> $GITHUB_STEP_SUMMARY
