apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Application reconciliation timeout
  timeout.reconciliation: 180s

  # Enable anonymous access for metrics
  statusbadge.enabled: "true"

  # Resource customizations for better health checks
  resource.customizations: |
    argoproj.io/Application:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs

  # Repository credentials (optional - can be configured via UI or CLI)
  # repositories: |
  #   - url: https://github.com/daylook/trial-workflow
  #     passwordSecret:
  #       name: github-repo-secret
  #       key: password
